"""Add is_internal to Response

Revision ID: 13e5ede2e0b0
Revises: 9b44bd354b99
Create Date: 2025-10-29 12:55:01.511318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e5ede2e0b0'
down_revision = '9b44bd354b99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_internal', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('is_internal')

    # ### end Alembic commands ###
