"""Add service_id to CannedResponse

Revision ID: 263073cb515c
Revises: 1673a5ce705d
Create Date: 2025-10-22 12:51:46.994230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '263073cb515c'
down_revision = '1673a5ce705d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canned_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        # ITO ANG BINAGO: Naglagay tayo ng pangalan sa 'None'
        batch_op.create_foreign_key('fk_canned_response_service_id_service', 'service', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canned_response', schema=None) as batch_op:
        # Ginamit natin yung parehong pangalan
        batch_op.drop_constraint('fk_canned_response_service_id_service', type_='foreignkey') 
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
