"""Add device_type_other column

Revision ID: 340c84903824
Revises: eeb40bbc80e0
Create Date: 2025-10-07 12:01:26.320531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '340c84903824'
down_revision = 'eeb40bbc80e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_type_other', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('device_type_other')

    # ### end Alembic commands ###
