"""Add assigned_staff to Ticket

Revision ID: 9b44bd354b99
Revises: 5ac377a1e5ea
Create Date: 2025-10-29 08:32:43.305079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b44bd354b99'
down_revision = '5ac377a1e5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_staff_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_staff_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_staff_id')

    # ### end Alembic commands ###
