"""Add dpds_remarks column to ticket

Revision ID: 9fb4e4aceeab
Revises: 340c84903824
Create Date: 2025-10-08 08:11:45.074665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb4e4aceeab'
down_revision = '340c84903824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dpds_remarks', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('dpds_remarks')

    # ### end Alembic commands ###
