"""Initial migration with tickets and users

Revision ID: a0f7e2aa691b
Revises: 
Create Date: 2025-10-07 10:37:07.973521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f7e2aa691b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_email', sa.String(length=120), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_details', sa.Text(), nullable=True),
    sa.Column('document_title', sa.String(length=255), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=100), nullable=True),
    sa.Column('school_id', sa.String(length=50), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=True),
    sa.Column('personnel_first_name', sa.String(length=100), nullable=True),
    sa.Column('personnel_middle_name', sa.String(length=100), nullable=True),
    sa.Column('personnel_last_name', sa.String(length=100), nullable=True),
    sa.Column('ext_name', sa.String(length=10), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.String(length=50), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('existing_email_or_na', sa.String(length=120), nullable=True),
    sa.Column('remarks', sa.String(length=255), nullable=True),
    sa.Column('contact_number', sa.String(length=50), nullable=True),
    sa.Column('document_type_other', sa.String(length=255), nullable=True),
    sa.Column('position_other', sa.String(length=255), nullable=True),
    sa.Column('remarks_other', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('ticket')
    # ### end Alembic commands ###
