"""Add CannedResponse model

Revision ID: ac308b10e7df
Revises: f492b9efba3b
Create Date: 2025-10-22 12:00:31.143277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac308b10e7df'
down_revision = 'f492b9efba3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canned_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.Text(), nullable=False))
        batch_op.drop_column('body')
        batch_op.drop_column('title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canned_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('body', sa.TEXT(), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
