"""Add fields for Personnel department

Revision ID: eeb40bbc80e0
Revises: a0f7e2aa691b
Create Date: 2025-10-07 11:10:07.066393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeb40bbc80e0'
down_revision = 'a0f7e2aa691b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('date_of_last_appointment', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('date_of_last_appointment')
        batch_op.drop_column('employee_number')

    # ### end Alembic commands ###
